services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: forex
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/forex
    depends_on:
      - db

volumes:
  db-data:
